name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y libsecp256k1-dev
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run test
        run: |
          ./ci-test.sh

